const sdkjds = {
    "IDCTE": 0,
    "CODEMPRESA": 2,
    "UFEMISSAOCTE": "RN",
    "CODUFEMPRESA": "CE",
    "IDREMETENTE": 567080,
    "IDDESTINATARIO": 567085,
    "IDCONTRATANTE": 567085,
    "CODCFOP": 6352,
    "MODELO": 57,
    "SERIE": 1,
    "DATAEMISSAO": "2026-05-02T15:51:04",
    "TIPOEMIS": 1,
    "TIPOIMP": 1,
    "CDV": 4,
    "CCT": "04605578",
    "TIPOAMB": 1,
    "TIPOCTE": 0,
    "MODAL": "01",
    "TIPOSERV": 0,
    "RETIRA": 1,
    "VALORRECEBER": 900.87,
    "VALORSERVICO": 900.87,
    "DESCCARGA": "DIVERSOS",
    "TIPOCARGA": "DIVERSOS",
    "VALORCARGA": 15861.53,
    "CODCIDADEEMISSAOCTE": 2408102,
    "CODCIDADEINISERV": 2408102,
    "CODCIDADEFIMSERV": 2309607,
    "NOMECIDADEEMISSAO": "NATAL",
    "NOMECIDADEINICIOSERV": "NATAL",
    "NOMECIDADEFIMSERV": "PACAJUS",
    "UFINISERV": "RN",
    "UFFIMSERV": "CE",
    "TIPOCONTRATANTE": 3,
    "ICMS_CST": "00",
    "CSTPIS": null,
    "CSTCOFINS": null,
    "ICMS_PREDBC": 0.0,
    "ICMS_VALORBC": 900.87,
    "ICMS_ALIQICMS": 12.0,
    "ICMS_VALORICMS": 108.11,
    "ICMS_VALORCREDPRESOUTORGADO": 0.0,
    "VALORINSS": 0.0,
    "VALORIR": 0.0,
    "VALORCOFINS": 0.0,
    "VALORPIS": 0.0,
    "PCOFINS": 0.0,
    "PPIS": 0.0,
    "VBCCOFINS": 0.0,
    "VBCPIS": 0.0,
    "VALORCSLL": 0.0,
    "VALORCARGAAVERB": 0.0,
    "NUMERACAOMANUAL": false,
    "GERAOBSMOTVEICULO": false,
    "GERAETIQUETAVOL": false,
    "GERAFINANCEIRO": false,
    "TIPOOPERACAOCTE": false,
    "ALTERTOMADOR": false,
    "EDITATRIBUTACAO": true,
    "EDITAVALORPRESTACAO": false,
    "ORIGEMSISTEMA": "CTE",
    "INSSRETIDO": false,
    "TRIBRETIDO": false,
    "SOMAICMSTOTAL": false,
    "STATUS": "N",
    "IDVEICULO": 60945,
    "IDMOTORISTA": 1348418,
    "VERSAO": "4.00",
    "USERALTER": "FINANCEIRO",
    "DATAALTER": "2026-04-16T17:48:04.787",
    "ICMSOUTRAUF": false,
    "SOMANFEVALORCARGA": false,
    "VALORCARGADisabled": false,
    "BUSCACRESULTADO": false,
    "EDITAVLRREC": true,
    "CTEXMLPESOLIQUIDO": false,
    "PESOKG": 1273.0,
    "IDPARAMCTE": 61579,
    "DOCNF": [],
    "DOCNFE": [
        {
            "IDENT": 10724040,
            "IDCTE": 4605578,
            "CHAVENFE": "24260407332190000789550010007674661356074952",
            "VALORNFE": null,
            "PESOB": null,
            "PESOL": null,
            "PIN": null,
            "DATAPREVENTREGA": null,
            "PITEM": 0.5,
            "NNF": "000767466",
            "NCM": null,
            "DESCPRODUTO": null
        },
        {
            "IDENT": 10724041,
            "IDCTE": 4605578,
            "CHAVENFE": "24260407332190000789550010007674841139723578",
            "VALORNFE": null,
            "PESOB": null,
            "PESOL": null,
            "PIN": null,
            "DATAPREVENTREGA": null,
            "PITEM": 0.5,
            "NNF": "000767484",
            "NCM": null,
            "DESCPRODUTO": null
        }
    ],
    "Financeiro": {
        "Rateios": [],
        "Parcelas": []
    },
    "CARGAQTD": [
        {
            "IDENT": 6699633,
            "SEQUENCIAL": 1,
            "IDCTE": 4605578,
            "UNIDADE": "01",
            "QUANTIDADE": 1273.0,
            "DESCMEDIDA": "01 - KG",
            "DESCUNIDADE": "KG",
            "EDITADO": false
        }
    ],
    "MODALRODO": {
        "IDENT": 5447898,
        "IDCTE": 4605578,
        "RNTC": "53841655",
        "DATAPREVENTREGA": "0001-01-01T00:00:00",
        "INDLOTACAO": 0,
    },
    "MODALDUTO": {
        "IDENT": 0,
        "IDCTE": 0,
    },
    "MODALAQUA": {
        "IDENT": 0,
        "IDCTE": 0,
    },
    "MODALAEREO": {
        "ProdPeri": [],
        "IDENT": 0,
        "IDCTE": 0,
    },
    "MODALMULTI": {
        "IDENT": 0,
        "IDCTE": 0,
        "INDNEGOCIAVEL": false
    },
    "PERCURSO": [],
    "INFOFISCO": [],
    "INFOOBS": [
        {
            "IDENT": 377565,
            "IDCTE": 4605578,
            "ORDEM": 0,
            "DESCCAMPO": "Campo1",
            "OBSERVACOES": "COMPLEMENTANDO CTE 341 PARA VALOR DE TABELA",
        }
    ],
    "IBSCBS": {
        "CST": "000",
        "cClassTrib": "000001",
        "pIBSUF": 0.1,
        "pCBS": 0.9,
        "vBC": 900.87,
        "vIBSUF": 0.9,
        "vIBS": 0.9,
        "vCBS": 8.11,
        "EDITADO": true,
        "SEQUENCIAL": 0,
    },
    "EXPEDIDOROBRIGATORIO": false,
    "RECEBEDOROBRIGATORIO": false,
    "SEQIMPORTACAO": 0,
    "UTILIZACRESULTADO": false,
    "UTILIZACCUSTO": false,
    "UTILIZADEPARTAMENTO": false,
    "TIPOSAVE": 0,
    "OPERACAO": "NOVO",
    "USERCREATE": "FINANCEIRO",
    "IDEMPRESA": 41291,
    "ERRO": false,
    "HUBNOTFY": false
}