export interface XML {
    cpf_motorista: string,
    cpfCnpjDestinatario: string,
    cpfCnpjRemetente: string,
    quantidadeCarga: string,
    valorCarga: string,
    valorServico: number,
    produtoPredominante: string,
    placaVeiculoTração: string,
    nome_motorista: string,
    nome_veiculo: string,
    nome_remetente: string,
    nome_destinatario: string,
    numeroNotaFiscal: string,
    chaveNotaFiscal: string,
    percentualCBS: string,
    valorIBS: string,
    valorICMS: string,
    saida: { city: string, uf: string },
    destino: { city: string, uf: string },
    fone_destinatario: string
    cidade_destinatario: string
    email_destinatario: string,
    nome_fantasia: string
    cep_destinatario: string
    rua_destinatario: string
    bairro_destinario: string
    numero_endereco_destinatario: string
    complemente_destinatario: string
    cidade_estado_destinatario: string,
    CODCIDADE: number,
    Uf_destinatario: string,
    INSCESTADUAL_destinatario: string
}


export interface CRLV {
    tipoVeiculo: string,
    tipoRodado: string,
    rntc_veículo: string,
    tipoCarroceria: string,
    tipoProprietario: string,
    proprietario: string,
    local: string,
    cpf_proprietario: string,
    categoria: string,
    validade: string,
    renavam: string,
    placa: string,
    carroceria: string,
    modelo: string,
    capacidade: string,
    peso: string,
    rntc_proprietatio: string
    nome_motorista: string,
    cpf_motorista: string,
    rntc_motorista: string
}


export interface CTE {
    "CCT": "00521157",
    "IDREMETENTE": 160370,
    "CODCIDADEFIMSERV": number,
    "CODCIDADEEMISSAOCTE": number,
    'CODCIDADEINISERV': number,
    "IDDESTINATARIO": 147428,
    "IDCONTRATANTE": 160370,
    "UFEMISSAOCTE": "CE",
    "CODUFEMPRESA": "CE",
    "VALORRECEBER": number, // 7819.36,
    "VALORSERVICO": number, // 7819.36,
    "DESCCARGA": string,
    "TIPOCARGA": string,
    "OBSVEICMOTVEIC": string,
    "VALORCARGA": number,
    "NOMECIDADEEMISSAO": "FORTALEZA",
    "NOMECIDADEINICIOSERV": "FORTALEZA",
    "NOMECIDADEFIMSERV": "SANTA CRUZ",
    "UFINISERV": string // "CE",
    "UFFIMSERV": string //"RN",
    "ICMS_VALORBC": number, // 7819.36,
    "ICMS_VALORICMS": number, // 938.32,
    "IDVEICULO": 35689,
    "IDMOTORISTA": 329749,
    "PESOKG": number//13700,
    "PLACATRACAO": "MCD0615",
    "DOCNFE": {
        "IDENT": number,
        "IDCTE": number,
        "CHAVENFE": string,
        "NNF": string
    }[]
    ,
    "CARGAQTD": [
        {
            "IDENT": 784468,
            "IDCTE": 521157,
            "UNIDADE": "01",
            "QUANTIDADE": number // 32000,
            "DESCMEDIDA": "01 - KG",
            "DESCUNIDADE": "KG",
        }
    ],
    "MODALRODO": {
        "IDENT": 591517,
        "IDCTE": 521157,
        "RNTC": "05857366",
        "DATAPREVENTREGA": "0001-01-01T00:00:00",
        "INDLOTACAO": 0,
        "CIOT": null,
        "TAF": null,
        "NROREGESTADUAL": null
    },
    "Veiculos": [
        {
            "IDENT": number,
            "IDCTE": number,
            "CODVEICULO": null,
            "RENAVAN": string,
            "PLACA": string,
            "TARA": number,
            "CAPACIDADEKG": number,
            "CAPACIDADEM3": number,
            "PROPRIO": boolean,
            "TIPOVEICULO": string,
            "UFLICENCIADO": string,
            "RNTC": string,
            "TIPOPROPRIETARIO": number,
            "IDVEICULO": number,
            'TIPORODADO': string,
            'TIPOCARROCERIA': string,
            'CPFCNPJ': string,
            'NOMEPROPRIETARIO': string,
            'INSCESTADUAL': string,
            'UFINSCESTADUAL': string
        }
    ],
    "IBSCBS": {
        "vBC": number, // 7819.36,
        "vIBSUF": number, // 7.82,
        "vIBS": number, // 7.82,
        "vCBS": number, // 70.37,
    },
}



// {
//     "IDCTE": 0,
//     "CODEMPRESA": 1,
//     "UFEMISSAOCTE": "CE",
//     "CODUFEMPRESA": "CE",
//     "NUMCTE": null,
//     "IDTOMADOR": null,
//     "IDREMETENTE": 160370,
//     "IDEXPEDIDOR": null,
//     "IDRECEBEDOR": null,
//     "IDDESTINATARIO": 338700,
//     "IDCONTRATANTE": null,
//     "CODCFOP": 5352,
//     "JRDIDTABFRETE": null,
//     "IDTIPOCARGA": null,
//     "NUMEIXOSINDISPONIVEL": null,
//     "MODELO": 57,
//     "SERIE": 1,
//     "DATAEMISSAO": "2026-06-27T16:43:11",
//     "TIPOEMIS": "1",
//     "TIPOIMP": "1",
//     "CDV": 0,
//     "CCT": null,
//     "TIPOAMB": "1",
//     "TIPOCTE": "0",
//     "MODAL": "01",
//     "TIPOSERV": "0",
//     "RETIRA": 1,
//     "RETIRADETALHE": null,
//     "OBSERVACOES": null,
//     "OBSERVACOESAUTO": null,
//     "VALORRECEBER": 0.02,
//     "VALORSERVICO": 0.02,
//     "DESCCARGA": "FARINHA",
//     "TIPOCARGA": "FARINHA",
//     "VALORCARGA": 0,
//     "CODCIDADEEMISSAOCTE": 2304400,
//     "CODCIDADEINISERV": 2304400,
//     "CODCIDADEFIMSERV": 3170206,
//     "NOMECIDADEEMISSAO": null,
//     "NOMECIDADEINICIOSERV": null,
//     "NOMECIDADEFIMSERV": null,
//     "UFINISERV": null,
//     "UFFIMSERV": null,
//     "TIPOCONTRATANTE": "0",
//     "ICMS_CST": "00",
//     "CSTPIS": null,
//     "CSTCOFINS": null,
//     "ICMS_PREDBC": 0,
//     "ICMS_VALORBC": 0.03,
//     "ICMS_ALIQICMS": 12,
//     "ICMS_VALORICMS": 0.04,
//     "ICMS_VALORCREDPRESOUTORGADO": 0,
//     "VALORINSS": 0,
//     "VALORIR": 0,
//     "VALORCOFINS": 0,
//     "VALORPIS": 0,
//     "PCOFINS": 0,
//     "PPIS": 0,
//     "VBCCOFINS": 0,
//     "VBCPIS": 0,
//     "VALORCSLL": 0,
//     "VALORCARGAAVERB": null,
//     "IDSEGURO": null,
//     "VALORTRIBFEDERAL": null,
//     "NUMERACAOMANUAL": false,
//     "GERAOBSMOTVEICULO": true,
//     "GERAETIQUETAVOL": false,
//     "GERAFINANCEIRO": false,
//     "TIPOOPERACAOCTE": false,
//     "ALTERTOMADOR": false,
//     "IDCONDPGTO": null,
//     "CODFORMAPGTO": null,
//     "CHAVECTECOMP": null,
//     "CHAVECTEANU": null,
//     "EDITATRIBUTACAO": true,
//     "EDITAVALORPRESTACAO": false,
//     "DATAHORAINIVIAGEM": null,
//     "TIPOFRETAMENTO": null,
//     "RESPSEGURO": null,
//     "CHAVECTE": null,
//     "INDGLOBALIZADO": null,
//     "ORIGEMSISTEMA": "CTE",
//     "IDRELAC": [],
//     "INSSRETIDO": false,
//     "TRIBRETIDO": false,
//     "SOMAICMSTOTAL": false,
//     "STATUS": "N",
//     "STATUSNOME": null,
//     "UNIDADE": null,
//     "PESOVOLUMES": null,
//     "QTDVOLUMES": null,
//     "FISCO": null,
//     "DATAHORASAIDA": null,
//     "DATAHORACHEGADA": null,
//     "CEPORIG": null,
//     "ENDERECOORIG": null,
//     "COMPLEMENTOORIG": null,
//     "BAIRROORIG": null,
//     "NUMEROORIG": null,
//     "CODCIDADEORIG": null,
//     "CEPDEST": null,
//     "ENDERECODEST": null,
//     "COMPLEMENTODEST": null,
//     "BAIRRODEST": null,
//     "NUMERODEST": null,
//     "CODCIDADEDEST": null,
//     "IDCRESULTADO": null,
//     "IDDEPARTAMENTO": null,
//     "IDCCUSTO": null,
//     "IDCONTACAIXA": null,
//     "IDVEICULO": null,
//     "IDMOTORISTA": 303516,
//     "OBSVEICMOTVEIC": null,
//     "OBSPARAMCTE": null,
//     "VERSAO": "4.00",
//     "USERALTER": null,
//     "DATAALTER": null,
//     "ICMSOUTRAUF": false,
//     "SOMANFEVALORCARGA": false,
//     "VALORCARGADisabled": false,
//     "BUSCACRESULTADO": false,
//     "EDITAVLRREC": false,
//     "CTEXMLPESOLIQUIDO": false,
//     "IDTIPOOPERACAOTP": null,
//     "vICMSDeson": null,
//     "cBenef": null,
//     "PESOKG": null,
//     "IDPARAMFISCALCTE": null,
//     "IDPARAMCTE": 6996,
//     "PLACATRACAO": null,
//     "PLACAREBOQUE": null,
//     "INFVEICULO": false,
//     "INFMOTORISTA": false,
//     "GERARECEB": false,
//     "GERAEXP": false,
//     "DOCNF": [],
//     "DOCNFE": [],
//     "DOCDCE": [],
//     "DOCOU": [],
//     "DOCANT": [],
//     "DOCREF": [],
//     "Financeiro": {
//         "Rateios": [],
//         "Parcelas": []
//     },
//     "OrdemColetaAssoc": [],
//     "VeicNovos": [],
//     "CompFrete": [],
//     "CARGAQTD": [
//         {
//             "IDENT": 1,
//             "SEQUENCIAL": 0,
//             "IDCTE": 0,
//             "UNIDADE": "01",
//             "QUANTIDADE": 1,
//             "TIPOMEDIDA": null,
//             "DESCMEDIDA": "01 - KG",
//             "DESCUNIDADE": null,
//             "EDITADO": false
//         }
//     ],
//     "MODALRODO": {
//         "IDENT": 0,
//         "IDCTE": 0,
//         "RNTC": "05857366",
//         "DATAPREVENTREGA": "0001-01-01T00:00:00",
//         "INDLOTACAO": 0,
//         "CIOT": null,
//         "TAF": null,
//         "NROREGESTADUAL": null
//     },
//     "MODALDUTO": {
//         "IDENT": 0,
//         "IDCTE": 0,
//         "vTar": null,
//         "dIni": null,
//         "dFim": null
//     },
//     "MODALAQUA": {
//         "IDENT": 0,
//         "IDCTE": 0,
//         "vPrest": null,
//         "vAFRMM": null,
//         "xNavio": null,
//         "balsa": null,
//         "nViag": null,
//         "direc": null,
//         "irin": null
//     },
//     "MODALAEREO": {
//         "ProdPeri": [],
//         "IDENT": 0,
//         "IDCTE": 0,
//         "nMinu": null,
//         "nOCA": null,
//         "dPrevAereo": null,
//         "xDime": null,
//         "cInfManu": null,
//         "CL": null,
//         "cTar": null,
//         "vTar": null
//     },
//     "MODALMULTI": {
//         "IDENT": 0,
//         "IDCTE": 0,
//         "COTM": null,
//         "INDNEGOCIAVEL": false
//     },
//     "PERCURSO": [],
//     "INFOFISCO": [],
//     "INFOOBS": [],
//     "Veiculos": [
//         {
//             "IDENT": 0,
//             "IDCTE": 0,
//             "CODVEICULO": null,
//             "RENAVAN": null,
//             "PLACA": null,
//             "TARA": 0,
//             "CAPACIDADEKG": 0,
//             "CAPACIDADEM3": 0,
//             "PROPRIO": false,
//             "TIPOVEICULO": "T",
//             "TIPORODADO": null,
//             "TIPOCARROCERIA": null,
//             "UFLICENCIADO": null,
//             "CPFCNPJ": null,
//             "RNTC": null,
//             "NOMEPROPRIETARIO": null,
//             "INSCESTADUAL": null,
//             "UFINSCESTADUAL": null,
//             "TIPOPROPRIETARIO": 1,
//             "IDVEICULO": 31457
//         }
//     ],
//     "Especies": [],
//     "IcmsPart": [],
//     "OrigDest": null,
//     "InfComp": null,
//     "CTE_GTVE": [],
//     "CTE_PRODPERI": [],
//     "IBSCBS": {
//         "CST": "000",
//         "cClassTrib": "000001",
//         "pIBSUF": null,
//         "pIBSMun": null,
//         "pCBS": null,
//         "cCredPres": null,
//         "pIBSCredPres": null,
//         "pCBSCredPres": null,
//         "tpCredPresIBSZFM": null,
//         "vBC": 5,
//         "vDevTrib": null,
//         "vIBSUF": 6,
//         "vIBSMun": null,
//         "vIBS": null,
//         "vCBS": null,
//         "vCredPres": null,
//         "vCredPresCondSus": null,
//         "EDITADO": true,
//         "SEQUENCIAL": 0,
//         "pDifIBSUF": null,
//         "pRedAliqIBSUF": null,
//         "vDifIBSUF": null,
//         "pAliqEfetIBSUF": null,
//         "pDifIBSMun": null,
//         "pRedAliqIBSMun": null,
//         "vDifIBSMun": null,
//         "pAliqEfetIBSMun": null,
//         "pDifCBS": null,
//         "pRedAliqCBS": null,
//         "vDifCBS": null,
//         "pAliqEfetCBS": null
//     },
//     "EXPEDIDOROBRIGATORIO": false,
//     "RECEBEDOROBRIGATORIO": false,
//     "SEQIMPORTACAO": 0,
//     "UTILIZACRESULTADO": false,
//     "UTILIZACCUSTO": false,
//     "UTILIZADEPARTAMENTO": false,
//     "IDFILA": null,
//     "CODIGO2FA": null,
//     "TIPOSAVE": 0,
//     "CHAVEACESSO": null,
//     "OPERACAO": "NOVO",
//     "CODUSUARIO": "SAMILA",
//     "USERCREATE": null,
//     "MSG": null,
//     "IDEMPRESA": 144458,
//     "returnTo": null,
//     "NOTEDITABLE": null,
//     "ERRO": false,
//     "HUBNOTFY": false,
//     "ERRORS": [],
//     "EGSPENDENCIA": null,
//     "IDArray": []
// }