export interface XML {
    cpf_motorista: string,
    cpfCnpjDestinatario: string,
    cpfCnpjRemetente: string,
    quantidadeCarga: string,
    valorCarga: string,
    valorServico: number,
    produtoPredominante: string,
    placaVeiculoTração: string,
    nome_motorista: string,
    nome_veiculo: string,
    nome_remetente: string,
    nome_destinatario: string,
    numeroNotaFiscal: string,
    chaveNotaFiscal: string,
    percentualCBS: string,
    valorIBS: string,
    valorICMS: string,
    saida: { city: string, uf: string },
    destino: { city: string, uf: string },
}


export interface CRLV {
    tipoVeiculo: string,
    tipoRodado: string,
    rntc_veículo: string,
    tipoCarroceria: string,
    tipoProprietario: string,
    proprietario: string,
    local: string,
    cpf_proprietario: string,
    categoria: string,
    validade: string,
    renavam: string,
    placa: string,
    carroceria: string,
    modelo: string,
    capacidade: string,
    peso: string,
    rntc_proprietatio: string
    nome_motorista: string,
    cpf_motorista: string,
    rntc_motorista: string
}


export interface CTE {
    "CCT": "00521157",
    "IDREMETENTE": 160370,
    "CODCIDADEFIMSERV": number,
    "CODCIDADEEMISSAOCTE": number,
    'CODCIDADEINISERV': number,
    "IDDESTINATARIO": 147428,
    "IDCONTRATANTE": 160370,
    "UFEMISSAOCTE": "CE",
    "CODUFEMPRESA": "CE",
    "VALORRECEBER": number, // 7819.36,
    "VALORSERVICO": number, // 7819.36,
    "DESCCARGA": string,
    "TIPOCARGA": string,
    "VALORCARGA": number,
    "NOMECIDADEEMISSAO": "FORTALEZA",
    "NOMECIDADEINICIOSERV": "FORTALEZA",
    "NOMECIDADEFIMSERV": "SANTA CRUZ",
    "UFINISERV": string // "CE",
    "UFFIMSERV": string //"RN",
    "ICMS_VALORBC": number, // 7819.36,
    "ICMS_VALORICMS": number, // 938.32,
    "IDVEICULO": 35689,
    "IDMOTORISTA": 329749,
    "OBSVEICMOTVEIC": "Veiculo: OCQ2A52\nMotorista: EDIGLEY PINHEIRO DIAS",
    "PESOKG": number//13700,
    "PLACATRACAO": "MCD0615",
    "DOCNFE": [
        {
            "IDENT": 1076745,
            "IDCTE": 521157,
            "CHAVENFE": string,
            "NNF": string,
        }
    ],
    "CARGAQTD": [
        {
            "IDENT": 784468,
            "IDCTE": 521157,
            "UNIDADE": "01",
            "QUANTIDADE": number // 32000,
            "DESCMEDIDA": "01 - KG",
            "DESCUNIDADE": "KG",
        }
    ],
    "MODALRODO": {
        "IDENT": 591517,
        "IDCTE": 521157,
        "RNTC": "05857366",
        "DATAPREVENTREGA": "0001-01-01T00:00:00",
        "INDLOTACAO": 0,
        "CIOT": null,
        "TAF": null,
        "NROREGESTADUAL": null
    },
    "Veiculos": [
        {
            "IDENT": number,
            "IDCTE": number,
            "CODVEICULO": null,
            "RENAVAN": string,
            "PLACA": string,
            "TARA": number,
            "CAPACIDADEKG": number,
            "CAPACIDADEM3": number,
            "PROPRIO": boolean,
            "TIPOVEICULO": string,
            "UFLICENCIADO": string,
            "RNTC": string,
            "TIPOPROPRIETARIO": number,
            "IDVEICULO": number,
            'TIPORODADO': string,
            'TIPOCARROCERIA': string,
            'CPFCNPJ': string,
            'NOMEPROPRIETARIO': string,
            'INSCESTADUAL': string,
            'UFINSCESTADUAL': string
        }
    ],
    "IBSCBS": {
        "vBC": number, // 7819.36,
        "vIBSUF": number, // 7.82,
        "vIBS": number, // 7.82,
        "vCBS": number, // 70.37,
    },
}