export let sendObj = {
    "IDCTE": 0,
    "CODEMPRESA": 1,
    "UFEMISSAOCTE": "CE",
    "CODUFEMPRESA": "CE",
    "NUMCTE": null,
    "IDTOMADOR": null,
    "IDREMETENTE": 567083,
    "IDEXPEDIDOR": null,
    "IDRECEBEDOR": null,
    "CODCFOP": 6352,
    "JRDIDTABFRETE": null,
    "IDTIPOCARGA": null,
    "NUMEIXOSINDISPONIVEL": null,
    "MODELO": 57,
    "SERIE": 1,
    "TIPOEMIS": "1",
    "TIPOIMP": "1",
    "CDV": 2,
    "CCT": "04630010",
    "TIPOAMB": "1",
    "TIPOCTE": "0",
    "TIPOSERV": "0",
    "RETIRA": 1,
    "RETIRADETALHE": "00",
    "OBSERVACOES": null,
    "OBSERVACOESAUTO": null,
    "MODAL": "01",
    //alterar aqui
    "VALORCARGAAVERB": 0, // -> quantidade carga
    "IDDESTINATARIO": 0,
    
    "IDCONTRATANTE": 567080,
    // https://api.egssistemas.com.br/EGSCTE//api/ComboBox/GCADASTRO {
    //     "search": "07.332.190/0007-89",
    //     "id": null,
    //     "propertyList": []
    // },
    //res:
    //     [
    //     {
    //         "CODIGO": 4,
    //         "NOME": "VICUNHA TEXTIL UND I",
    //         "CPFCNPJ": "07.332.190/0012-46",
    //         "INSCESTADUAL": "068206283",
    //         "NOMEMUNICIPIO": "MARACANAU",
    //         "CODESTADO": "CE",
    //         "RAZAOSOCIAL": "VICUNHA TEXTIL S/A.",
    //         "IDCADASTRO": 567083,
    //         "CODCIDADE": 2307650,
    //         "IDVENDEDOR": null,
    //         "IDTRANSPORTADOR": null,
    //         "FONE": null,
    //         "EMAIL": null,
    //         "CONTATO": null,
    //         "CELULAR": null,
    //         "MODFRETE": null,
    //         "CODFORMAPGTO": null,
    //         "IDCONDPGTO": null,
    //         "CODCFOP": null,
    //         "IDTABFRETE": null,
    //         "CONTRIBUINTEICMS": 1,
    //         "CONSUMIDORFINAL": false,
    //         "FISJUR": false,
    //         "CEP": "61901410",
    //         "IDENTFILTRO": 1
    //     }
    // ]
    "DATAEMISSAO": new Date().toISOString(),
    "VALORRECEBER": 5,
    "VALORSERVICO": 7,
    "VALORCARGA": 123,
    "DESCCARGA": "FIO",
    "TIPOCARGA": "FIO",

    //ate aqui
    "CODCIDADEEMISSAOCTE": 2307650,
    "CODCIDADEINISERV": 2307650,
    "CODCIDADEFIMSERV": 2408102,
    "NOMECIDADEEMISSAO": "MARACANAU",
    "NOMECIDADEINICIOSERV": "MARACANAU",
    "NOMECIDADEFIMSERV": "NATAL",
    "UFINISERV": "CE",
    "UFFIMSERV": "RN",
    "TIPOCONTRATANTE": "3",
    "ICMS_CST": "00",
    "CSTPIS": null,
    "CSTCOFINS": null,
    "ICMS_PREDBC": 0,
    "ICMS_VALORBC": 5762.4,
    "ICMS_ALIQICMS": 12,
    "ICMS_VALORICMS": 691.49,
    "ICMS_VALORCREDPRESOUTORGADO": 0,
    "VALORINSS": 0,
    "VALORIR": 0,
    "VALORCOFINS": 0,
    "VALORPIS": 0,
    "PCOFINS": 0,
    "PPIS": 0,
    "VBCCOFINS": 0,
    "VBCPIS": 0,
    "VALORCSLL": 0,

    "IDSEGURO": null,
    "VALORTRIBFEDERAL": null,
    "NUMERACAOMANUAL": false,
    "GERAOBSMOTVEICULO": false,
    "GERAETIQUETAVOL": false,
    "GERAFINANCEIRO": false,
    "TIPOOPERACAOCTE": false,
    "ALTERTOMADOR": false,
    "IDCONDPGTO": null,
    "CODFORMAPGTO": null,
    "CHAVECTECOMP": null,
    "CHAVECTEANU": null,
    "EDITATRIBUTACAO": true,
    "EDITAVALORPRESTACAO": false,
    "DATAHORAINIVIAGEM": null,
    "TIPOFRETAMENTO": null,
    "RESPSEGURO": null,
    "CHAVECTE": null,
    "INDGLOBALIZADO": false,
    "ORIGEMSISTEMA": "CTE",
    "IDRELAC": [],
    "INSSRETIDO": false,
    "TRIBRETIDO": false,
    "SOMAICMSTOTAL": false,
    "STATUS": "N",
    "UNIDADE": null,
    "PESOVOLUMES": null,
    "QTDVOLUMES": null,
    "FISCO": null,
    "DATAHORASAIDA": null,
    "DATAHORACHEGADA": null,
    "CEPORIG": null,
    "ENDERECOORIG": null,
    "COMPLEMENTOORIG": null,
    "BAIRROORIG": null,
    "NUMEROORIG": null,
    "CODCIDADEORIG": null,
    "CEPDEST": null,
    "ENDERECODEST": null,
    "COMPLEMENTODEST": null,
    "BAIRRODEST": null,
    "NUMERODEST": null,
    "CODCIDADEDEST": null,
    "IDCRESULTADO": 2668,
    "IDDEPARTAMENTO": null,
    "IDCCUSTO": null,
    "IDCONTACAIXA": null,
    "IDVEICULO": 85512,
    "IDMOTORISTA": 769498,
    "OBSVEICMOTVEIC": null,
    "VERSAO": "4.00",
    "USERALTER": "FINANCEIRO",
    "DATAALTER": "2026-04-28T20:15:08.753",
    "ICMSOUTRAUF": false,
    "SOMANFEVALORCARGA": false,
    "VALORCARGADisabled": false,
    "BUSCACRESULTADO": false,
    "EDITAVLRREC": true,
    "CTEXMLPESOLIQUIDO": false,
    "IDTIPOOPERACAOTP": null,
    "vICMSDeson": null,
    "cBenef": null,
    "PESOKG": 13883.33,
    "IDPARAMFISCALCTE": null,
    "IDPARAMCTE": 61579,
    "DOCNF": [],
    "DOCNFE": [
        {
            "IDENT": 10761759,
            "IDCTE": 4630010,
            "CHAVENFE": "23260407332190001246550010007808441710302873",
            "VALORNFE": null,
            "PESOB": null,
            "PESOL": null,
            "PIN": null,
            "DATAPREVENTREGA": null,
            "PITEM": 0.2,
            "NNF": "000780844",
            "NCM": null,
            "DESCPRODUTO": null
        }
    ],
    "DOCOU": [],
    "DOCANT": [],
    "DOCREF": [],
    "Financeiro": {
        "Rateios": [],
        "Parcelas": []
    },
    "OrdemColetaAssoc": [],
    "VeicNovos": [],
    "CompFrete": [],
    "CARGAQTD": [
        {
            "IDENT": 6735850,
            "SEQUENCIAL": 1,
            "IDCTE": 4630010,
            "UNIDADE": "01",
            "QUANTIDADE": 0,
            "TIPOMEDIDA": null,
            "DESCMEDIDA": "01 - KG",
            "DESCUNIDADE": "KG",
            "EDITADO": false
        }
    ],

    //
    // https://api.egssistemas.com.br/EGSCTE//api/ComboBox/CarregamentoSimples
    //      {
    //    "name": "CTeUnidCarga",
    //  "search": "01",
    //"id": null,
    //"propertyList": []
    //}
    //res: [{"CODIGO":"02","DESCRICAO":"02 - TON"}]
    "MODALRODO": {
        "IDENT": 5474883,
        "IDCTE": 4630010,
        "RNTC": "53841655",
        "DATAPREVENTREGA": "0001-01-01T00:00:00",
        "INDLOTACAO": 0,
        "CIOT": null,
        "TAF": null,
        "NROREGESTADUAL": null
    },
    "MODALDUTO": {
        "IDENT": 0,
        "IDCTE": 0,
        "vTar": null,
        "dIni": null,
        "dFim": null
    },
    "MODALAQUA": {
        "IDENT": 0,
        "IDCTE": 0,
        "vPrest": null,
        "vAFRMM": null,
        "xNavio": null,
        "balsa": null,
        "nViag": null,
        "direc": null,
        "irin": null
    },
    "MODALAEREO": {
        "ProdPeri": [],
        "IDENT": 0,
        "IDCTE": 0,
        "nMinu": null,
        "nOCA": null,
        "dPrevAereo": null,
        "xDime": null,
        "cInfManu": null,
        "CL": null,
        "cTar": null,
        "vTar": null
    },
    "MODALMULTI": {
        "IDENT": 0,
        "IDCTE": 0,
        "COTM": null,
        "INDNEGOCIAVEL": false
    },
    "PERCURSO": [],
    "INFOFISCO": [],
    "INFOOBS": [],
    "Veiculos": [
        {
            "IDENT": 0,
            "IDCTE": 0,
            "CODVEICULO": null,
            "RENAVAN": null,
            "PLACA": null,
            "TARA": 0,
            "CAPACIDADEKG": 0,
            "CAPACIDADEM3": 0,
            "PROPRIO": false,
            "TIPOVEICULO": null,
            "TIPORODADO": null,
            "TIPOCARROCERIA": null,
            "UFLICENCIADO": null,
            "CPFCNPJ": null,
            "RNTC": null,
            "NOMEPROPRIETARIO": null,
            "INSCESTADUAL": null,
            "UFINSCESTADUAL": null,
            "TIPOPROPRIETARIO": 0,
            "IDVEICULO": null
        }
    ],

    //
    // https://api.egssistemas.com.br/EGSCTE//api/ComboBox/GVEICULO?search=AKT2F24&tipoVeiculo=T
    // query => search: AKT2F24, tipoVeiculo: T
    // res:[
    //     {
    //         "IDENT": 143838,
    //         "PLACA": "AKT2F24",
    //         "UF": "SP",
    //         "TARA": 23.0,
    //         "DESCRICAO": "SCANIA/R124 GA4X2NZ 400",
    //         "MOTORISTA": null,
    //         "DATAPESAGEM": null,
    //         "STATUS": "N",
    //         "IDCADASTRO": 1153112,
    //         "VALORVEICULO": null,
    //         "PRAZODEPRECIACAO": null,
    //         "PROPRIO": false,
    //         "IDGRUPOVEICULO": 3,
    //         "IDVEICULO": 130786,
    //         "IDEMPRESA": 41291,
    //         "RENAVAN": "00799611131",
    //         "TIPOVEICULO": "T",
    //         "TIPORODADO": "03",
    //         "TIPOCARROCERIA": "00",
    //         "CAPACIDADEKG": null,
    //         "CAPACIDADEM": null,
    //         "TIPOPROPRIETARIO": 1,
    //         "DATACREATE": "2024-06-05T06:43:15.647",
    //         "USERCREATE": "FINANCEIRO",
    //         "DATAALTER": null,
    //         "USERALTER": null,
    //         "RNTC": "55915599",
    //         "IDPLANOMANUTVEIC": null,
    //         "ANO": null,
    //         "MODELO": null,
    //         "DATAAQUISICAO": null,
    //         "KMAQUISICAO": null,
    //         "IDMOTORISTA": null,
    //         "IDPROPVEICULO": 1153112,
    //         "KMATUAL": null,
    //         "DATAKMATUAL": null,
    //         "IDPRODUTO": null,
    //         "IDCCUSTO": null,
    //         "IDDEPARTAMENTO": null,
    //         "IDCRESULTADO": null,
    //         "UFINSCESTADUAL": "SP",
    //         "CODCADASTRO": 372,
    //         "INSCESTADUAL": null,
    //         "CODGRUPO": "03",
    //         "NOMEPROPRIETARIO": "VITORIA TRANSPORTE",
    //         "DESCGRUPOVEICULO": "Cavalo Mecânico",
    //         "VALORPEDAGIO": null,
    //         "CPFCNPJ": "09581459000109",
    //         "DESCTIPORODADO": "Cavalo Mecânico",
    //         "DESCTIPOCARROCERIA": "não aplicável",
    //         "DESCTIPOVEICULO": "Tração",
    //         "DESCTIPOPROPRIETARIO": "TAC - Independente",
    //         "DESCVEICULOTRACAO": null,
    //         "DESCPLANOMANUT": null,
    //         "CATCOMBVEICULAR": null,
    //         "IDENTFILTRO": 1
    //     }
    // ]
    "Especies": [],
    "IcmsPart": [],
    "OrigDest": null,
    "InfComp": null,
    "CTE_GTVE": [],
    "CTE_PRODPERI": [],
    "IBSCBS": {
        "CST": "000",
        "cClassTrib": "000001",
        "pIBSUF": 0.1,
        "pIBSMun": null,
        "pCBS": 0.9,
        "cCredPres": null,
        "pIBSCredPres": null,
        "pCBSCredPres": null,
        "tpCredPresIBSZFM": null,
        "vBC": 0,
        "vDevTrib": null,
        "vIBSUF": 0,
        "vIBSMun": null,
        "vIBS": 0,
        "vCBS": 51.86,
        "vCredPres": null,
        "vCredPresCondSus": null,
        "EDITADO": true,
        "SEQUENCIAL": 0,
        "pDifIBSUF": null,
        "pRedAliqIBSUF": null,
        "vDifIBSUF": null,
        "pAliqEfetIBSUF": null,
        "pDifIBSMun": null,
        "pRedAliqIBSMun": null,
        "vDifIBSMun": null,
        "pAliqEfetIBSMun": null,
        "pDifCBS": null,
        "pRedAliqCBS": null,
        "vDifCBS": null,
        "pAliqEfetCBS": null
    },
    "EXPEDIDOROBRIGATORIO": false,
    "RECEBEDOROBRIGATORIO": false,
    "SEQIMPORTACAO": 0,
    "UTILIZACRESULTADO": false,
    "UTILIZACCUSTO": false,
    "UTILIZADEPARTAMENTO": false,
    "IDFILA": null,
    "CODIGO2FA": null,
    "TIPOSAVE": 0,
    "CHAVEACESSO": null,
    "OPERACAO": "NOVO",
    "CODUSUARIO": "FINANCEIRO",
    "USERCREATE": "FINANCEIRO",
    "MSG": null,
    "IDEMPRESA": 41291,
    "returnTo": null,
    "NOTEDITABLE": null,
    "ERRO": false,
    "HUBNOTFY": false,
    "ERRORS": [],
    "EGSPENDENCIA": null,
    "IDArray": []
}

// fetch("https://api.egssistemas.com.br/EGSCTE//api/CteApi/Salvar", {
//     "headers": {
//         "accept": "application/json, text/plain, */*",
//         "accept-language": "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7,id;q=0.6,pt-PT;q=0.5,es;q=0.4,tr;q=0.3",
//         "authorization": "Bearer jJi_mFSa4FZ-KQpvSlRGZ42GidNBOVFrbCgvZwUp4ZQMnL_myu-Zhvs7evbZ9BxcLhEJ_GhS3bGnP4rk29sGtGY7QO3jzUlWiw4m4041_-447PyD2L6uSu8M9HQ0GyO-HlzqKXJWwlNIf9gLfZ64KCFtd0j3ig942YBxgU91Sz2klBbDn_QSU2SZ6LkoiCaT1LY9WqLVDq0S7qadEkemJcscmq7bkCgpbQv3ictySG1zTauqE_U7xps0donOm5pMRN0cyrWWvIuwRLjBYV9P-ghgGFDCHeNrWBf5VxPnjqCNtMTDtakOUfrOvpYwE56-QFGJCWHModvHT01FDlmwyoD4lmLKO-huQDT4JfpFnt8umdlBWaVmef_Kk_vDqPbfRQ-o4HGUAwuPJMh7gHfi7rWmbX-_j-ojwqyx4NggJ0eDDh89owcWvpCZjti3ZKkT1K4b5egV_DkLD2q-5uGH8vInllh8P0lC_ibzCJyUzOjZDbRRwnI89KBEPszN42FefNcJUweS_p6TBb8LQjVhEUEC2wy4y4bUpRSVhbFuJ1s",
//         "content-type": "application/json;charset=UTF-8",
//         "priority": "u=1, i",
//         "sec-ch-ua": "\"Chromium\";v=\"146\", \"Not-A.Brand\";v=\"24\", \"Opera GX\";v=\"130\"",
//         "sec-ch-ua-mobile": "?0",
//         "sec-ch-ua-platform": "\"Windows\"",
//         "sec-fetch-dest": "empty",
//         "sec-fetch-mode": "cors",
//         "sec-fetch-site": "same-site",
//         "x-user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36 OPR/130.0.0.0",
//         "Referer": "https://app.egssistemas.com.br/"
//     },
//     "body": JSON.stringify(obj),
//     "method": "POST"
// });